# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(40, 110, 75, 23))
        self.button.setObjectName("button")
        self.content = QtWidgets.QTextBrowser(Form)
        self.content.setGeometry(QtCore.QRect(180, 40, 256, 192))
        self.content.setObjectName("content")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button.setText(_translate("Form", "故宫"))
